name: projet-1

# Variables d'environnement globales
env:
  SERVER_USER: "root"
  SERVER_IP: "20.47.71.43"

  # Gestion de la concurrence des jobs
  concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Événements déclenchant le workflow
on:
  push:
    branches:
      - main # Branche "main"

# Jobs à exécuter
jobs:
  # Job pour les vérifications backend
  checks_backend:
    runs-on: ubuntu-latest # Exécution sur la dernière version d'Ubuntu
    steps:
      - name: Checkout le code
        uses: actions/checkout@v4
      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: server/package-lock.json
      - name: Installer les dépendances
        run: npm ci --prefer-offline
      - name: Exécuter les tests
        run: npm run test:ci
      - name: Vérification des vulnérabilités
        run: npm audit
      - name: Upload rapport de couverture sur Codecov
        uses: codecov/codecov-action@v3

  # Job pour les vérifications frontend
  checks_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout le code
        uses: actions/checkout@v4
      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: client/package-lock.json
      - name: Installer les dépendances
        run: cd client && npm ci --prefer-offline
      - name: Vérification des vulnérabilités
        run: cd client && npm audit
      - name: Linting du code
        run: cd client && npm run lint

  # Job pour construire le frontend
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout le code
        uses: actions/checkout@v4
      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: client/package-lock.json
      - name: Installer les dépendances
        run: cd client && npm ci --prefer-offline
      - name: Build du frontend
        run: cd client && npm run build
      - name: Upload de l'artéfact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: frontend-dist
          path: client/dist/
          retention-days: 1

  test_e2e:
    runs-on: ubuntu-latest
    needs: [build_frontend]
    steps:
      - name: checkout le code
        uses: actions/checkout@v4
      - name: télécharger l'artéfact du frontend
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: client/dist/
      - name: installer Node.js
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: server/package-lock.json
      - name: installer les dépendances serveur
        run: |
          cd server
          npm ci --prefer-offline
      - name: lancer le serveur backend
        run: |
          cd server
          node index.js &
      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-
      # Cypress ⚠️
      - name: Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: client
          browser: chrome
          start: npm run preview
          wait-on: http://localhost:4173
          wait-on-timeout: 60
          config: baseUrl=http://localhost:4173

  # Job pour le déploiement
  deploy:
    needs: [checks_backend, checks_frontend, build_frontend] # Dépend des jobs précédents
    runs-on: ubuntu-latest
    steps:
      - name: Checkout le code
        uses: actions/checkout@v4
      - name: Télécharger l'artéfact
        uses: actions/download-artifact@v3
        with:
          name: frontend-dist
          path: ./dist
      - name: Déployer sur le serveur
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< "${{secrets.AZURE_PROD_PKEY}}"
          mkdir -p ~/.ssh
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          scp -r ./dist/* $SERVER_USER@$SERVER_IP:/var/www/client
          scp -r ./server $SERVER_USER@$SERVER_IP:/var/www
          ssh $SERVER_USER@$SERVER_IP "cd /var/www/server && npm install --omit=dev"
          ssh $SERVER_USER@$SERVER_IP "cd /var/www/server && pm2 startOrRestart ecosystem.config.js --env production && pm2 save"
